version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pacha-net
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres
    privileged: true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pacha-net
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api

  # Redis pour les tâches asynchrones
  redis:
    image: redis:6-alpine
    networks:
      - pacha-net
    restart: unless-stopped

  # PostgreSQL pour OpenVAS et Metasploit
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=msf
      - POSTGRES_USER=msf
      - POSTGRES_PASSWORD=msf123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pacha-net
    restart: unless-stopped

  # OpenVAS Scanner
  openvas:
    image: immauss/openvas:latest
    ports:
      - "9392:9392"
    volumes:
      - openvas_data:/data
    networks:
      - pacha-net
    environment:
      - USERNAME=admin
      - PASSWORD=admin123
    restart: unless-stopped

  # Metasploit avec base de données
  metasploit:
    image: metasploitframework/metasploit-framework:latest
    depends_on:
      - postgres
    volumes:
      - ./data/metasploit:/root/.msf4
      - ./reports:/reports
    networks:
      - pacha-net
    environment:
      - DATABASE_URL=postgres://msf:msf123@postgres:5432/msf
    command: tail -f /dev/null
    restart: unless-stopped

  # DVWA pour les tests
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
    networks:
      - pacha-net
    restart: unless-stopped

networks:
  pacha-net:
    driver: bridge

volumes:
  openvas_data:
  postgres_data: