
version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    networks:
      - pacha-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pacha-net
    environment:
      - NODE_ENV=development

networks:
  pacha-net:
    driver: bridge

