version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pacha-postgres
    environment:
      POSTGRES_DB: pacha_toolbox
      POSTGRES_USER: pacha_user
      POSTGRES_PASSWORD: pacha_secure_2024!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: pacha-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pacha_toolbox
      - DB_USER=pacha_user
      - DB_PASSWORD=pacha_secure_2024!
      - ADMIN_PASSWORD=Admin123!
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app:rw
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: pacha-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
